---
- name: check if disk initiated 
  shell: /sbin/blkid {{ new_disk }} 
  register: disk_init
  ignore_errors: true

- name:  mkfs
  shell: /sbin/mkfs.ext4 {{ new_disk }}
  when: "'ext4'not in disk_init.stdout"

- name: mount {{ new_disk }} as /var/lib/docker
  mount: name={{ dest_dir }} src={{ new_disk }} fstype=ext4 state=mounted 
